name: fsm-local-mongodb

services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mongodb-data:/data/db
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d:ro

volumes:
  mongodb-data:
    name: backend_mongodb-data
    external: true
