spring:
  application:
    name: admin-server
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mariadb://localhost:3306/fsm_command}
    username: ${SPRING_R2DBC_USERNAME:fsm}
    password: ${SPRING_R2DBC_PASSWORD:fsm}
  codec:
    max-in-memory-size: 1MB
  webflux:
    multipart:
      max-in-memory-size: 1MB
      max-disk-usage-per-part: 10MB
      max-parts: 20
management:
  endpoints:
    web:
      exposure:
        include: health,info
security:
  jwt:
    issuer: ${SECURITY_JWT_ISSUER:dev.riss.fsm}
    secret: ${SECURITY_JWT_SECRET}
    access-token-ttl-seconds: ${SECURITY_JWT_ACCESS_TOKEN_TTL:3600}
server:
  port: ${SERVER_PORT:8081}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
