spring:
  application:
    name: admin-server
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mariadb://localhost:3306/fsm_command}
    username: ${SPRING_R2DBC_USERNAME:fsm}
    password: ${SPRING_R2DBC_PASSWORD:fsm}
management:
  endpoints:
    web:
      exposure:
        include: health,info
security:
  jwt:
    issuer: ${SECURITY_JWT_ISSUER:dev.riss.fsm}
    secret: ${SECURITY_JWT_SECRET}
    access-token-ttl-seconds: ${SECURITY_JWT_ACCESS_TOKEN_TTL:3600}
server:
  port: ${SERVER_PORT:8081}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
